version: '3.5'
services:
    postgres:
        restart: always
        image: postgres:10
        env_file:
            - db-config.env
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - products_network

    mongodb:
        restart: always
        image: mongo
        container_name: mongodb
        volumes:
            - mongo-data:/data/db
        ports:
            - "27018:27017"
        networks:
            - products_network

    app:
        restart: always
        build: .
        tty: true   # output za testovite, probaj bez 
        ports:    
            - 5000:5000
        volumes:
            - .:/project
        depends_on: 
            - postgres
            - mongodb
        # entrypoint: ["python", "app.py"]
        networks: 
            - products_network

networks:
  products_network:
    external:
      name: project_network

volumes:
  db-data:
    driver: local
  mongo-data:
    driver: local