---
apiVersion: argoproj.io/v1alpha1
kind: EventSource     # tuka definirame event source, vo slucajov github webhook (listener)
metadata:
  name: github-event-source 
  namespace: argo-events
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  github:
    products-webhook:      # imeto na github webhook (listenerot), eventName actually (custom, kako sakame)
      owner: ekrajchevska
      repository: flask-products
      webhook:
        endpoint: /products-ms
        port: "12000"
        method: POST
        url: http://localhost
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
      insecure: true
      active: true
      contentType: json