apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-products-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-products
  template:
    metadata:
      labels:
        app: flask-products
    spec:
      hostNetwork: true
      containers:
        - name: products-databases
          image: evgenija1/products-databases:v10
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_PORT
            - name: POSTGRES_DATABASE_FLASK
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_DATABASE_FLASK

            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key:  MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key:  MONGO_PORT
            
          resources:
            requests:
              memory: 100Mi
              cpu: 100m